nohup: ignoring input
Experiment dir : search-Jacobian-20211213-153427
12/13 03:34:31 PM gpu device = 0
12/13 03:34:31 PM args = Namespace(arch_learning_rate=0.0003, arch_weight_decay=0.001, aux_loss_weight=10.0, batch_size=64, cutout=False, cutout_length=16, data='/mnt/xiayufeng_v0/data', debug=False, drop_path_prob=0.3, epochs=50, gpu=0, grad_clip=5, greedy=0, init_channels=16, l2=0, layers=8, learning_rate=0.025, learning_rate_min=0.001, model_path='saved_models', momentum=0.9, name='runs', report_freq=50, save='search-Jacobian-20211213-153427', seed=2, sep_loss='l2', single_level=False, train_portion=0.5, weight_decay=0.0003)
12/13 03:34:36 PM param size = 1.930618MB
Files already downloaded and verified
12/13 03:34:37 PM epoch 0 lr 2.495266e-02
12/13 03:34:37 PM genotype = Genotype(normal=[('skip_connect', 0), ('skip_connect', 1), ('skip_connect', 0), ('skip_connect', 1), ('skip_connect', 0), ('skip_connect', 1), ('skip_connect', 0), ('skip_connect', 1)], normal_concat=range(2, 6), reduce=[('skip_connect', 0), ('skip_connect', 1), ('skip_connect', 0), ('skip_connect', 1), ('skip_connect', 0), ('skip_connect', 1), ('skip_connect', 0), ('skip_connect', 1)], reduce_concat=range(2, 6))
/usr/local/lib/python3.6/dist-packages/torch/optim/lr_scheduler.py:136: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
/usr/local/lib/python3.6/dist-packages/torch/optim/lr_scheduler.py:509: UserWarning: To get the last learning rate computed by the scheduler, please use `get_last_lr()`.
  "please use `get_last_lr()`.", UserWarning)
12/13 03:34:44 PM train 000 5.782487e+02 10.937500 46.875000
/mnt/sunjialiang/AAAD/optimizer_adv/nasp/separate_loss.py:16: UserWarning: Using a target size (torch.Size([])) that is different to the input size (torch.Size([14, 16])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  loss2 = -F.mse_loss(input2, torch.tensor(0.5, requires_grad=False).cuda())
/mnt/sunjialiang/AAAD/noise/jacobian.py:71: UserWarning: This overload of addcdiv is deprecated:
	addcdiv(Tensor input, Number value, Tensor tensor1, Tensor tensor2, *, Tensor out)
Consider using one of the following signatures instead:
	addcdiv(Tensor input, Tensor tensor1, Tensor tensor2, *, Number value, Tensor out) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  v = torch.addcdiv(arxilirary_zero, 1.0, v, vnorm)
train_search_Jacobian.py:204: UserWarning: torch.nn.utils.clip_grad_norm is now deprecated in favor of torch.nn.utils.clip_grad_norm_.
  nn.utils.clip_grad_norm(model.parameters(), args.grad_clip)
12/13 03:39:04 PM train 050 1.662477e+01 10.049020 50.245098
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 03:43:37 PM train 100 9.516213e+00 10.380569 50.154703
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 03:48:02 PM train 150 7.115071e+00 10.088990 50.258692
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 03:52:32 PM train 200 5.908638e+00 10.144590 50.163246
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 03:57:00 PM train 250 5.182844e+00 10.227839 50.168078
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 04:01:37 PM train 300 4.698348e+00 10.106935 49.953281
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 04:06:18 PM train 350 4.351789e+00 10.073896 49.728454
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 04:10:13 PM train time 2135.920543
12/13 04:10:13 PM alphas_time 236.408667 
12/13 04:10:13 PM forward_time 111.895355
12/13 04:10:13 PM backward_time 1330.700418
12/13 04:10:13 PM train_acc 10.112000
12/13 04:10:14 PM valid 000 2.307469e+00 3.125000 43.750000
12/13 04:10:27 PM valid 050 2.303160e+00 9.773284 50.643382
12/13 04:10:40 PM valid 100 2.302644e+00 10.194926 50.758045
12/13 04:10:53 PM valid 150 2.303542e+00 9.944123 50.051738
12/13 04:11:06 PM valid 200 2.303634e+00 9.965796 50.287624
12/13 04:11:19 PM valid 250 2.303575e+00 9.891683 50.255229
12/13 04:11:32 PM valid 300 2.303639e+00 9.883721 50.285507
12/13 04:11:45 PM valid 350 2.303445e+00 9.958155 50.485221
12/13 04:11:55 PM inference time 102.387572
12/13 04:11:55 PM valid_acc 10.036000
12/13 04:11:55 PM alphas_normal = tensor([[0.4882, 0.4642, 0.5285, 0.4899, 0.4651, 0.4475, 0.5261, 0.6219],
        [0.4181, 0.4136, 0.4563, 0.4711, 0.4183, 0.5195, 0.5012, 0.6219],
        [0.4355, 0.4166, 0.5377, 0.4449, 0.4301, 0.5736, 0.5020, 0.6219],
        [0.4257, 0.4102, 0.5295, 0.4470, 0.4226, 0.4204, 0.5547, 0.6219],
        [0.4056, 0.4017, 0.4018, 0.5754, 0.4042, 0.5347, 0.5657, 0.6219],
        [0.4219, 0.4046, 0.5383, 0.4399, 0.4129, 0.4284, 0.4296, 0.6219],
        [0.4250, 0.4089, 0.4801, 0.5850, 0.4207, 0.5473, 0.4483, 0.6219],
        [0.4041, 0.4022, 0.5512, 0.4204, 0.4049, 0.5074, 0.4246, 0.6219],
        [0.4103, 0.4006, 0.5714, 0.5737, 0.4028, 0.4709, 0.4839, 0.6219],
        [0.4361, 0.4266, 0.4528, 0.4375, 0.4225, 0.4482, 0.5640, 0.6219],
        [0.4155, 0.4136, 0.4676, 0.4743, 0.4148, 0.4412, 0.5690, 0.6219],
        [0.4050, 0.4067, 0.5896, 0.5618, 0.4035, 0.5573, 0.4978, 0.6219],
        [0.4142, 0.4089, 0.4879, 0.5453, 0.4069, 0.5672, 0.5083, 0.6219],
        [0.4117, 0.4064, 0.5049, 0.5196, 0.4051, 0.4507, 0.5606, 0.6219]],
       device='cuda:0', requires_grad=True)
12/13 04:11:55 PM alphas_reduce = tensor([[0.4839, 0.4359, 0.5257, 0.5278, 0.4746, 0.5713, 0.5541, 0.6219],
        [0.4825, 0.5268, 0.5130, 0.4516, 0.5584, 0.5555, 0.5034, 0.6219],
        [0.5487, 0.4353, 0.4383, 0.4455, 0.4952, 0.4533, 0.4988, 0.6219],
        [0.4993, 0.5011, 0.5193, 0.4394, 0.5539, 0.4633, 0.4908, 0.6219],
        [0.5456, 0.4112, 0.5138, 0.5539, 0.5207, 0.5604, 0.4722, 0.6219],
        [0.5354, 0.4432, 0.4819, 0.4741, 0.4759, 0.5504, 0.5758, 0.6219],
        [0.4591, 0.5336, 0.5511, 0.5559, 0.5588, 0.5162, 0.4355, 0.6219],
        [0.5557, 0.4493, 0.4723, 0.4891, 0.5275, 0.5512, 0.4966, 0.6219],
        [0.4922, 0.4289, 0.5211, 0.4360, 0.4696, 0.4708, 0.4149, 0.6219],
        [0.4838, 0.5585, 0.5198, 0.4955, 0.5647, 0.4553, 0.4401, 0.6219],
        [0.5707, 0.5006, 0.5150, 0.5535, 0.5276, 0.4757, 0.5573, 0.6219],
        [0.5766, 0.5085, 0.4674, 0.5396, 0.5688, 0.5223, 0.4580, 0.6219],
        [0.5659, 0.4662, 0.4703, 0.4759, 0.5590, 0.4459, 0.4161, 0.6219],
        [0.5713, 0.4903, 0.4865, 0.4378, 0.5641, 0.5632, 0.5266, 0.6219]],
       device='cuda:0', requires_grad=True)
12/13 04:11:55 PM epoch 1 lr 2.483464e-02
12/13 04:11:55 PM genotype = Genotype(normal=[('none', 1), ('none', 0), ('none', 1), ('none', 2), ('none', 0), ('none', 2), ('none', 0), ('none', 1)], normal_concat=range(2, 6), reduce=[('none', 0), ('none', 1), ('none', 0), ('none', 1), ('none', 3), ('none', 0), ('none', 3), ('none', 0)], reduce_concat=range(2, 6))
train_search_Jacobian.py:224: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  input = Variable(input, volatile=True).cuda()
train_search_Jacobian.py:225: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  target = Variable(target, volatile=True).cuda()
12/13 04:12:01 PM train 000 2.264044e+00 10.937500 50.000000
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 04:16:49 PM train 050 2.265506e+00 9.742647 50.245098
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 04:21:48 PM train 100 2.265269e+00 10.179455 50.819926
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 04:27:00 PM train 150 2.265062e+00 9.902732 50.858858
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 04:32:07 PM train 200 2.265332e+00 10.020211 50.583022
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 04:37:28 PM train 250 2.265408e+00 9.848108 50.354831
12/13 04:42:28 PM train 300 2.265281e+00 9.800664 50.389327
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 04:47:41 PM train 350 2.265368e+00 9.820157 50.222578
12/13 04:52:00 PM train time 2405.207951
12/13 04:52:00 PM alphas_time 251.980799 
12/13 04:52:00 PM forward_time 113.054562
12/13 04:52:00 PM backward_time 1386.870502
12/13 04:52:00 PM train_acc 9.840000
12/13 04:52:02 PM valid 000 2.298053e+00 10.937500 51.562500
12/13 04:52:14 PM valid 050 2.303839e+00 9.834559 49.724265
12/13 04:52:27 PM valid 100 2.303567e+00 9.839109 49.938119
12/13 04:52:40 PM valid 150 2.303913e+00 9.716474 49.958609
12/13 04:52:53 PM valid 200 2.303546e+00 9.965796 50.023321
12/13 04:53:07 PM valid 250 2.303577e+00 9.947709 49.863048
12/13 04:53:20 PM valid 300 2.303606e+00 9.940822 49.880606
12/13 04:53:32 PM valid 350 2.303627e+00 9.882479 49.897614
12/13 04:53:43 PM inference time 102.149241
12/13 04:53:43 PM valid_acc 9.852000
12/13 04:53:43 PM alphas_normal = tensor([[0.4764, 0.4181, 0.5385, 0.4844, 0.4364, 0.4244, 0.5368, 0.7499],
        [0.3681, 0.3491, 0.4422, 0.4671, 0.3659, 0.5091, 0.4961, 0.7499],
        [0.4014, 0.3524, 0.5717, 0.3981, 0.3933, 0.6225, 0.4912, 0.7499],
        [0.3773, 0.3381, 0.5407, 0.3955, 0.3691, 0.3656, 0.5729, 0.7499],
        [0.3373, 0.3183, 0.3299, 0.6177, 0.3304, 0.5700, 0.6149, 0.7499],
        [0.3596, 0.3226, 0.5807, 0.4042, 0.3474, 0.3658, 0.3728, 0.7499],
        [0.3714, 0.3321, 0.4836, 0.6556, 0.3606, 0.5797, 0.4044, 0.7499],
        [0.3347, 0.3204, 0.5856, 0.3627, 0.3322, 0.5124, 0.3653, 0.7499],
        [0.3431, 0.3136, 0.6096, 0.6065, 0.3212, 0.4817, 0.4545, 0.7499],
        [0.4054, 0.3703, 0.4275, 0.3989, 0.3773, 0.3921, 0.6061, 0.7499],
        [0.3706, 0.3595, 0.4175, 0.4673, 0.3679, 0.3876, 0.6145, 0.7499],
        [0.3465, 0.3410, 0.6550, 0.5845, 0.3379, 0.6137, 0.4968, 0.7499],
        [0.3673, 0.3435, 0.4797, 0.5771, 0.3454, 0.6022, 0.5044, 0.7499],
        [0.3610, 0.3365, 0.4944, 0.5272, 0.3390, 0.3985, 0.6019, 0.7499]],
       device='cuda:0', requires_grad=True)
12/13 04:53:43 PM alphas_reduce = tensor([[0.4529, 0.4016, 0.5415, 0.5410, 0.4767, 0.6202, 0.5880, 0.7499],
        [0.4514, 0.5598, 0.4863, 0.3976, 0.6105, 0.5711, 0.5023, 0.7499],
        [0.5778, 0.4019, 0.3986, 0.4152, 0.5084, 0.4233, 0.5104, 0.7499],
        [0.5023, 0.5022, 0.5063, 0.3910, 0.5904, 0.4296, 0.4990, 0.7499],
        [0.5521, 0.3430, 0.5481, 0.6084, 0.5078, 0.5942, 0.4487, 0.7499],
        [0.5610, 0.4107, 0.4781, 0.4442, 0.4747, 0.5906, 0.6343, 0.7499],
        [0.4307, 0.5740, 0.5843, 0.5974, 0.6099, 0.5193, 0.3871, 0.7499],
        [0.5997, 0.4246, 0.4287, 0.5108, 0.5588, 0.5972, 0.5035, 0.7499],
        [0.5046, 0.3989, 0.5361, 0.3870, 0.4811, 0.4580, 0.3528, 0.7499],
        [0.4770, 0.6026, 0.5509, 0.5283, 0.6108, 0.4649, 0.4005, 0.7499],
        [0.6193, 0.5143, 0.5342, 0.5916, 0.5494, 0.4693, 0.6034, 0.7499],
        [0.6125, 0.4927, 0.4418, 0.5707, 0.5960, 0.5487, 0.4231, 0.7499],
        [0.5956, 0.4517, 0.4642, 0.4765, 0.5949, 0.4102, 0.3623, 0.7499],
        [0.6051, 0.4854, 0.4742, 0.3989, 0.6006, 0.6100, 0.5391, 0.7499]],
       device='cuda:0', requires_grad=True)
12/13 04:53:43 PM epoch 2 lr 2.467010e-02
12/13 04:53:43 PM genotype = Genotype(normal=[('none', 1), ('none', 0), ('none', 1), ('none', 2), ('none', 0), ('none', 2), ('none', 0), ('none', 1)], normal_concat=range(2, 6), reduce=[('none', 1), ('none', 0), ('none', 0), ('none', 1), ('none', 3), ('none', 0), ('none', 3), ('none', 0)], reduce_concat=range(2, 6))
12/13 04:53:50 PM train 000 2.262511e+00 14.062500 48.437500
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 04:58:38 PM train 050 2.265931e+00 10.294118 49.264706
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 05:03:38 PM train 100 2.265581e+00 10.163985 49.241955
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 05:08:47 PM train 150 2.265490e+00 9.964818 49.368791
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 05:14:01 PM train 200 2.265540e+00 10.012438 49.619092
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 05:19:17 PM train 250 2.265583e+00 9.823207 49.396165
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 05:24:39 PM train 300 2.265540e+00 9.904485 49.444560
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 05:29:56 PM train 350 2.265475e+00 9.940349 49.594907
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 05:34:18 PM train time 2434.747728
12/13 05:34:18 PM alphas_time 250.192369 
12/13 05:34:18 PM forward_time 112.619438
12/13 05:34:18 PM backward_time 1383.368518
12/13 05:34:18 PM train_acc 9.944000
12/13 05:34:19 PM valid 000 2.297257e+00 14.062500 56.250000
12/13 05:34:32 PM valid 050 2.303245e+00 9.834559 50.612745
12/13 05:34:45 PM valid 100 2.303864e+00 10.024752 49.969059
12/13 05:34:59 PM valid 150 2.303952e+00 9.850993 49.886175
12/13 05:35:12 PM valid 200 2.303600e+00 9.950249 50.093284
12/13 05:35:26 PM valid 250 2.303898e+00 9.953934 49.670070
12/13 05:35:38 PM valid 300 2.303956e+00 9.821429 49.626246
12/13 05:35:51 PM valid 350 2.303911e+00 9.855769 49.701745
12/13 05:36:02 PM inference time 104.195930
12/13 05:36:02 PM valid_acc 9.928000
12/13 05:36:02 PM alphas_normal = tensor([[0.4641, 0.3704, 0.5476, 0.4749, 0.4141, 0.4044, 0.5360, 0.8799],
        [0.3404, 0.3032, 0.4454, 0.4762, 0.3357, 0.4789, 0.4903, 0.8799],
        [0.3894, 0.2991, 0.6013, 0.3588, 0.3812, 0.6558, 0.4632, 0.8799],
        [0.3487, 0.2827, 0.5386, 0.3561, 0.3369, 0.3250, 0.5744, 0.8799],
        [0.2900, 0.2472, 0.2746, 0.6489, 0.2748, 0.6161, 0.6275, 0.8799],
        [0.2986, 0.2427, 0.6201, 0.3898, 0.2894, 0.3183, 0.3380, 0.8799],
        [0.3512, 0.2757, 0.4781, 0.7051, 0.3336, 0.6084, 0.3780, 0.8799],
        [0.2864, 0.2501, 0.6086, 0.3161, 0.2788, 0.5071, 0.3218, 0.8799],
        [0.2962, 0.2403, 0.6366, 0.6292, 0.2595, 0.4871, 0.4184, 0.8799],
        [0.3942, 0.3239, 0.4144, 0.3604, 0.3548, 0.3500, 0.6260, 0.8799],
        [0.3548, 0.3237, 0.3599, 0.4793, 0.3468, 0.3524, 0.6448, 0.8799],
        [0.3118, 0.2910, 0.7178, 0.5918, 0.2931, 0.6683, 0.5096, 0.8799],
        [0.3437, 0.2953, 0.4743, 0.5979, 0.3086, 0.6123, 0.5108, 0.8799],
        [0.3325, 0.2847, 0.4773, 0.5268, 0.2944, 0.3556, 0.6290, 0.8799]],
       device='cuda:0', requires_grad=True)
12/13 05:36:02 PM alphas_reduce = tensor([[0.4153, 0.3760, 0.5520, 0.5589, 0.4804, 0.6553, 0.6035, 0.8799],
        [0.4044, 0.5847, 0.4643, 0.3722, 0.6500, 0.5760, 0.5061, 0.8799],
        [0.6057, 0.3734, 0.3780, 0.4163, 0.5152, 0.3974, 0.5191, 0.8799],
        [0.4972, 0.5037, 0.4727, 0.3562, 0.6191, 0.3981, 0.5163, 0.8799],
        [0.5476, 0.2947, 0.5712, 0.6444, 0.4939, 0.6194, 0.4499, 0.8799],
        [0.5736, 0.3875, 0.4916, 0.4170, 0.4740, 0.6230, 0.6772, 0.8799],
        [0.4022, 0.6094, 0.6175, 0.6365, 0.6514, 0.5176, 0.3525, 0.8799],
        [0.6318, 0.4161, 0.3892, 0.5318, 0.5898, 0.6336, 0.4923, 0.8799],
        [0.5085, 0.3845, 0.5395, 0.3512, 0.4958, 0.4509, 0.3127, 0.8799],
        [0.4808, 0.6470, 0.5936, 0.5751, 0.6526, 0.5008, 0.3745, 0.8799],
        [0.6551, 0.5371, 0.5568, 0.6116, 0.5691, 0.4791, 0.6523, 0.8799],
        [0.6378, 0.4985, 0.4231, 0.5874, 0.6188, 0.5775, 0.4003, 0.8799],
        [0.6195, 0.4610, 0.4805, 0.4867, 0.6320, 0.3839, 0.3230, 0.8799],
        [0.6319, 0.5020, 0.4662, 0.3694, 0.6376, 0.6507, 0.5479, 0.8799]],
       device='cuda:0', requires_grad=True)
12/13 05:36:02 PM epoch 3 lr 2.445969e-02
12/13 05:36:02 PM genotype = Genotype(normal=[('none', 1), ('none', 0), ('none', 1), ('none', 2), ('none', 0), ('none', 2), ('none', 0), ('none', 1)], normal_concat=range(2, 6), reduce=[('none', 1), ('none', 0), ('none', 0), ('none', 1), ('none', 3), ('none', 0), ('none', 3), ('none', 2)], reduce_concat=range(2, 6))
12/13 05:36:09 PM train 000 2.274946e+00 10.937500 34.375000
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 05:41:09 PM train 050 2.264957e+00 9.834559 50.674020
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 05:46:19 PM train 100 2.265292e+00 9.560644 50.386757
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 05:51:32 PM train 150 2.265165e+00 9.913079 50.620861
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 05:56:49 PM train 200 2.265191e+00 10.059080 50.528607
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 06:02:06 PM train 250 2.265247e+00 9.935259 50.336155
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 06:07:25 PM train 300 2.265324e+00 9.925249 50.347799
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 06:12:48 PM train 350 2.265418e+00 9.824608 50.151353
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 06:17:14 PM train time 2471.620423
12/13 06:17:14 PM alphas_time 254.179592 
12/13 06:17:14 PM forward_time 114.653797
12/13 06:17:14 PM backward_time 1401.733080
12/13 06:17:14 PM train_acc 9.868000
12/13 06:17:15 PM valid 000 2.299155e+00 10.937500 57.812500
12/13 06:17:28 PM valid 050 2.302949e+00 10.171569 50.490196
12/13 06:17:42 PM valid 100 2.303471e+00 9.715347 49.659653
12/13 06:17:55 PM valid 150 2.303697e+00 9.437086 49.441225
12/13 06:18:09 PM valid 200 2.303681e+00 9.647077 49.448072
12/13 06:18:23 PM valid 250 2.303530e+00 9.667580 49.526892
12/13 06:18:36 PM valid 300 2.303480e+00 9.686462 49.558762
12/13 06:18:49 PM valid 350 2.303369e+00 9.793447 49.732906
12/13 06:19:00 PM inference time 106.283432
12/13 06:19:00 PM valid_acc 9.852000
12/13 06:19:00 PM alphas_normal = tensor([[0.4537, 0.3309, 0.5512, 0.4661, 0.3985, 0.3892, 0.5223, 1.0000],
        [0.3173, 0.2640, 0.4576, 0.4897, 0.3112, 0.4353, 0.4837, 1.0000],
        [0.3870, 0.2577, 0.6242, 0.3251, 0.3785, 0.6812, 0.4431, 1.0000],
        [0.3231, 0.2332, 0.5316, 0.3061, 0.3082, 0.2923, 0.5744, 1.0000],
        [0.2528, 0.1875, 0.2272, 0.6650, 0.2293, 0.6721, 0.6219, 1.0000],
        [0.2515, 0.1765, 0.6488, 0.3779, 0.2480, 0.2901, 0.3136, 1.0000],
        [0.3523, 0.2329, 0.4672, 0.7372, 0.3264, 0.6269, 0.3421, 1.0000],
        [0.2536, 0.1958, 0.6360, 0.2829, 0.2423, 0.5101, 0.2860, 1.0000],
        [0.2631, 0.1823, 0.6679, 0.6344, 0.2134, 0.4922, 0.3884, 1.0000],
        [0.4032, 0.2907, 0.3983, 0.3426, 0.3507, 0.3394, 0.6456, 1.0000],
        [0.3565, 0.3015, 0.3345, 0.4936, 0.3443, 0.3341, 0.6519, 1.0000],
        [0.2894, 0.2536, 0.7731, 0.5988, 0.2602, 0.6972, 0.5467, 1.0000],
        [0.3359, 0.2636, 0.4742, 0.6148, 0.2931, 0.6102, 0.5051, 1.0000],
        [0.3154, 0.2423, 0.4613, 0.5253, 0.2620, 0.3111, 0.6376, 1.0000]],
       device='cuda:0', requires_grad=True)
12/13 06:19:00 PM alphas_reduce = tensor([[0.3977, 0.3659, 0.5591, 0.5798, 0.5012, 0.6743, 0.6202, 1.0000],
        [0.3507, 0.5893, 0.4586, 0.3692, 0.6683, 0.5699, 0.5142, 1.0000],
        [0.6180, 0.3586, 0.3668, 0.4423, 0.5356, 0.3943, 0.5375, 1.0000],
        [0.4836, 0.5009, 0.4316, 0.3263, 0.6380, 0.3690, 0.5317, 1.0000],
        [0.5591, 0.2671, 0.5968, 0.6798, 0.5059, 0.6229, 0.4622, 1.0000],
        [0.5638, 0.3847, 0.5248, 0.4008, 0.4966, 0.6413, 0.7112, 1.0000],
        [0.3769, 0.6295, 0.6507, 0.6820, 0.6737, 0.5191, 0.3268, 1.0000],
        [0.6653, 0.4186, 0.3690, 0.5508, 0.6278, 0.6652, 0.4776, 1.0000],
        [0.5168, 0.3802, 0.5473, 0.3167, 0.5179, 0.4408, 0.2917, 1.0000],
        [0.4945, 0.6922, 0.6278, 0.6171, 0.6995, 0.5431, 0.3615, 1.0000],
        [0.6800, 0.5482, 0.5686, 0.6285, 0.5757, 0.4880, 0.6914, 1.0000],
        [0.6584, 0.5086, 0.4196, 0.5930, 0.6414, 0.6121, 0.3922, 1.0000],
        [0.6294, 0.4691, 0.5095, 0.5091, 0.6590, 0.3550, 0.2995, 1.0000],
        [0.6483, 0.5218, 0.4732, 0.3497, 0.6703, 0.6893, 0.5549, 1.0000]],
       device='cuda:0', requires_grad=True)
12/13 06:19:01 PM epoch 4 lr 2.420423e-02
12/13 06:19:01 PM genotype = Genotype(normal=[('none', 1), ('none', 0), ('none', 1), ('none', 2), ('none', 0), ('none', 2), ('none', 0), ('none', 4)], normal_concat=range(2, 6), reduce=[('none', 1), ('none', 0), ('none', 0), ('none', 1), ('none', 3), ('none', 0), ('none', 3), ('none', 2)], reduce_concat=range(2, 6))
12/13 06:19:07 PM train 000 2.269551e+00 7.812500 48.437500
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 06:24:09 PM train 050 2.265847e+00 9.742647 50.245098
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 06:29:22 PM train 100 2.265624e+00 9.452351 49.597772
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 06:34:37 PM train 150 2.265579e+00 9.612997 49.399834
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 06:39:52 PM train 200 2.265685e+00 9.553794 49.284826
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 06:45:10 PM train 250 2.265648e+00 9.648904 49.445966
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 06:50:28 PM train 300 2.265675e+00 9.696844 49.403032
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 06:55:53 PM train 350 2.265617e+00 9.682158 49.470264
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 07:00:14 PM train time 2473.761852
12/13 07:00:16 PM alphas_time 253.742455 
12/13 07:00:16 PM forward_time 115.317405
12/13 07:00:16 PM backward_time 1404.076638
12/13 07:00:16 PM train_acc 9.724000
12/13 07:00:17 PM valid 000 2.300338e+00 14.062500 54.687500
12/13 07:00:30 PM valid 050 2.303997e+00 9.405637 48.927696
12/13 07:00:43 PM valid 100 2.303653e+00 9.823639 49.149134
12/13 07:00:57 PM valid 150 2.303324e+00 9.861341 49.637831
12/13 07:01:11 PM valid 200 2.303434e+00 9.825871 49.587998
12/13 07:01:24 PM valid 250 2.303270e+00 9.922809 49.875498
12/13 07:01:38 PM valid 300 2.303239e+00 9.904485 49.839078
12/13 07:01:51 PM valid 350 2.303340e+00 9.926994 49.697293
12/13 07:02:03 PM inference time 106.851772
12/13 07:02:03 PM valid_acc 9.852000
12/13 07:02:03 PM alphas_normal = tensor([[0.4403, 0.2967, 0.5414, 0.4487, 0.3828, 0.3707, 0.5157, 1.0000],
        [0.3051, 0.2407, 0.4697, 0.4933, 0.2990, 0.4057, 0.4838, 1.0000],
        [0.3998, 0.2306, 0.6354, 0.2983, 0.3899, 0.7047, 0.4168, 1.0000],
        [0.3079, 0.1948, 0.5175, 0.2671, 0.2913, 0.2561, 0.5577, 1.0000],
        [0.2300, 0.1419, 0.1859, 0.6739, 0.1981, 0.7129, 0.6062, 1.0000],
        [0.2099, 0.1196, 0.6710, 0.3677, 0.2131, 0.2651, 0.2966, 1.0000],
        [0.3707, 0.2107, 0.4647, 0.7651, 0.3378, 0.6384, 0.3293, 1.0000],
        [0.2367, 0.1570, 0.6542, 0.2668, 0.2229, 0.5097, 0.2574, 1.0000],
        [0.2413, 0.1382, 0.7068, 0.6394, 0.1823, 0.5023, 0.3644, 1.0000],
        [0.4138, 0.2639, 0.3826, 0.3250, 0.3550, 0.3258, 0.6675, 1.0000],
        [0.3682, 0.2914, 0.3047, 0.5051, 0.3538, 0.3194, 0.6477, 1.0000],
        [0.2787, 0.2266, 0.8112, 0.6069, 0.2398, 0.7308, 0.5745, 1.0000],
        [0.3313, 0.2373, 0.4775, 0.6304, 0.2866, 0.5998, 0.5053, 1.0000],
        [0.3044, 0.2099, 0.4597, 0.5147, 0.2391, 0.2816, 0.6470, 1.0000]],
       device='cuda:0', requires_grad=True)
12/13 07:02:03 PM alphas_reduce = tensor([[0.3804, 0.3616, 0.5548, 0.6011, 0.5234, 0.6844, 0.6295, 1.0000],
        [0.3006, 0.5896, 0.4628, 0.3804, 0.6860, 0.5614, 0.5253, 1.0000],
        [0.6424, 0.3460, 0.3694, 0.4778, 0.5529, 0.3958, 0.5539, 1.0000],
        [0.4818, 0.4948, 0.3965, 0.3054, 0.6560, 0.3378, 0.5608, 1.0000],
        [0.5619, 0.2450, 0.6156, 0.7096, 0.5162, 0.6256, 0.4687, 1.0000],
        [0.5489, 0.3920, 0.5640, 0.3873, 0.5266, 0.6505, 0.7366, 1.0000],
        [0.3550, 0.6404, 0.6775, 0.7275, 0.6900, 0.5122, 0.3118, 1.0000],
        [0.6912, 0.4228, 0.3498, 0.5673, 0.6598, 0.7038, 0.4542, 1.0000],
        [0.5247, 0.3776, 0.5532, 0.2900, 0.5408, 0.4414, 0.2787, 1.0000],
        [0.5116, 0.7414, 0.6644, 0.6663, 0.7496, 0.5837, 0.3457, 1.0000],
        [0.7073, 0.5637, 0.5893, 0.6381, 0.5925, 0.5041, 0.7282, 1.0000],
        [0.6756, 0.5252, 0.4075, 0.5926, 0.6682, 0.6528, 0.4009, 1.0000],
        [0.6446, 0.4876, 0.5460, 0.5432, 0.6976, 0.3288, 0.2857, 1.0000],
        [0.6641, 0.5504, 0.4883, 0.3220, 0.7098, 0.7289, 0.5604, 1.0000]],
       device='cuda:0', requires_grad=True)
12/13 07:02:03 PM epoch 5 lr 2.390474e-02
12/13 07:02:03 PM genotype = Genotype(normal=[('none', 1), ('none', 0), ('none', 1), ('none', 2), ('none', 0), ('none', 2), ('none', 4), ('none', 0)], normal_concat=range(2, 6), reduce=[('none', 1), ('none', 0), ('none', 1), ('none', 0), ('none', 3), ('none', 0), ('none', 3), ('none', 2)], reduce_concat=range(2, 6))
12/13 07:02:10 PM train 000 2.264026e+00 7.812500 48.437500
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 07:07:12 PM train 050 2.265099e+00 10.355392 49.754902
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 07:12:23 PM train 100 2.265247e+00 9.653465 50.216584
12/13 07:17:36 PM train 150 2.265344e+00 9.861341 49.886175
12/13 07:22:52 PM train 200 2.265243e+00 9.872512 49.852301
12/13 07:28:10 PM train 250 2.265379e+00 9.972610 49.520667
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 07:33:30 PM train 300 2.265378e+00 9.899294 49.626246
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 07:38:45 PM train 350 2.265379e+00 9.846866 49.652778
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 07:43:06 PM train time 2462.711582
12/13 07:43:06 PM alphas_time 251.023798 
12/13 07:43:06 PM forward_time 113.369575
12/13 07:43:06 PM backward_time 1399.558304
12/13 07:43:06 PM train_acc 9.920000
12/13 07:43:07 PM valid 000 2.300526e+00 9.375000 54.687500
12/13 07:43:20 PM valid 050 2.303114e+00 9.742647 50.337010
12/13 07:43:33 PM valid 100 2.303352e+00 9.885520 49.613243
12/13 07:43:46 PM valid 150 2.303211e+00 9.768212 49.658526
12/13 07:43:59 PM valid 200 2.303055e+00 9.810323 49.657960
12/13 07:44:13 PM valid 250 2.303122e+00 9.866783 49.694970
12/13 07:44:26 PM valid 300 2.303104e+00 9.847384 49.584718
12/13 07:44:39 PM valid 350 2.303028e+00 9.815705 49.777422
12/13 07:44:50 PM inference time 104.333071
12/13 07:44:50 PM valid_acc 9.852000
12/13 07:44:50 PM alphas_normal = tensor([[0.4444, 0.2759, 0.5258, 0.4332, 0.3824, 0.3435, 0.5062, 1.0000],
        [0.2985, 0.2260, 0.4839, 0.4918, 0.2931, 0.3818, 0.4841, 1.0000],
        [0.4171, 0.2097, 0.6406, 0.2768, 0.4050, 0.7173, 0.3973, 1.0000],
        [0.3028, 0.1676, 0.5041, 0.2318, 0.2826, 0.2264, 0.5428, 1.0000],
        [0.2180, 0.1066, 0.1451, 0.6730, 0.1796, 0.7476, 0.5895, 1.0000],
        [0.1901, 0.0775, 0.6797, 0.3617, 0.1982, 0.2446, 0.2631, 1.0000],
        [0.3922, 0.1921, 0.4594, 0.7846, 0.3529, 0.6478, 0.3297, 1.0000],
        [0.2328, 0.1313, 0.6827, 0.2607, 0.2186, 0.5101, 0.2291, 1.0000],
        [0.2234, 0.1003, 0.7441, 0.6316, 0.1571, 0.4996, 0.3419, 1.0000],
        [0.4376, 0.2511, 0.3680, 0.3268, 0.3713, 0.3231, 0.6826, 1.0000],
        [0.3766, 0.2842, 0.2761, 0.5278, 0.3612, 0.3074, 0.6343, 1.0000],
        [0.2815, 0.2151, 0.8424, 0.6180, 0.2364, 0.7516, 0.5892, 1.0000],
        [0.3301, 0.2171, 0.4789, 0.6413, 0.2889, 0.6010, 0.5102, 1.0000],
        [0.2980, 0.1841, 0.4625, 0.5171, 0.2235, 0.2559, 0.6498, 1.0000]],
       device='cuda:0', requires_grad=True)
12/13 07:44:50 PM alphas_reduce = tensor([[0.3718, 0.3601, 0.5402, 0.6172, 0.5433, 0.6919, 0.6407, 1.0000],
        [0.2614, 0.5892, 0.4744, 0.3946, 0.7027, 0.5509, 0.5321, 1.0000],
        [0.6735, 0.3384, 0.3737, 0.5105, 0.5714, 0.4005, 0.5734, 1.0000],
        [0.4704, 0.4956, 0.3549, 0.2800, 0.6799, 0.3148, 0.5912, 1.0000],
        [0.5676, 0.2310, 0.6453, 0.7309, 0.5318, 0.6221, 0.4678, 1.0000],
        [0.5460, 0.4073, 0.6104, 0.3793, 0.5588, 0.6562, 0.7681, 1.0000],
        [0.3300, 0.6633, 0.7051, 0.7734, 0.7159, 0.5077, 0.3026, 1.0000],
        [0.7157, 0.4368, 0.3409, 0.5901, 0.6946, 0.7402, 0.4306, 1.0000],
        [0.5354, 0.3853, 0.5755, 0.2663, 0.5645, 0.4354, 0.2770, 1.0000],
        [0.5341, 0.7885, 0.7043, 0.7136, 0.8012, 0.6235, 0.3354, 1.0000],
        [0.7399, 0.5724, 0.6003, 0.6458, 0.6092, 0.5227, 0.7577, 1.0000],
        [0.6911, 0.5461, 0.4065, 0.5906, 0.6973, 0.6939, 0.4081, 1.0000],
        [0.6551, 0.5081, 0.5911, 0.5865, 0.7331, 0.3081, 0.2780, 1.0000],
        [0.6761, 0.5788, 0.5087, 0.2935, 0.7487, 0.7697, 0.5726, 1.0000]],
       device='cuda:0', requires_grad=True)
12/13 07:44:50 PM epoch 6 lr 2.356240e-02
12/13 07:44:50 PM genotype = Genotype(normal=[('none', 1), ('none', 0), ('none', 1), ('none', 2), ('none', 0), ('none', 2), ('none', 4), ('none', 0)], normal_concat=range(2, 6), reduce=[('none', 1), ('none', 0), ('none', 1), ('none', 0), ('none', 3), ('none', 0), ('none', 3), ('none', 2)], reduce_concat=range(2, 6))
12/13 07:45:00 PM train 000 2.268605e+00 7.812500 46.875000
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 07:49:57 PM train 050 2.264476e+00 9.589461 50.796569
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 07:55:15 PM train 100 2.265113e+00 9.715347 50.541460
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 08:00:35 PM train 150 2.264923e+00 9.757864 50.724338
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 08:05:56 PM train 200 2.265103e+00 9.654851 50.497512
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 08:11:20 PM train 250 2.265175e+00 9.605329 50.168078
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 08:16:44 PM train 300 2.265184e+00 9.639743 50.098630
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 08:22:05 PM train 350 2.265263e+00 9.682158 50.004452
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 08:26:32 PM train time 2502.125935
12/13 08:26:32 PM alphas_time 260.819491 
12/13 08:26:32 PM forward_time 116.375122
12/13 08:26:32 PM backward_time 1418.195976
12/13 08:26:32 PM train_acc 9.756000
12/13 08:26:33 PM valid 000 2.303149e+00 4.687500 53.125000
12/13 08:26:48 PM valid 050 2.303707e+00 10.018382 49.662990
12/13 08:27:01 PM valid 100 2.303023e+00 9.993812 50.324876
12/13 08:27:15 PM valid 150 2.303158e+00 9.882036 50.196606
12/13 08:27:29 PM valid 200 2.302832e+00 10.066853 50.396455
12/13 08:27:43 PM valid 250 2.302788e+00 10.240289 50.354831
12/13 08:27:57 PM valid 300 2.302922e+00 10.184801 50.243978
12/13 08:28:11 PM valid 350 2.303050e+00 10.100605 50.106838
12/13 08:28:22 PM inference time 109.707338
12/13 08:28:22 PM valid_acc 10.084000
12/13 08:28:22 PM alphas_normal = tensor([[0.4569, 0.2676, 0.5107, 0.4030, 0.3943, 0.3144, 0.4910, 1.0000],
        [0.2939, 0.2134, 0.4997, 0.4835, 0.2907, 0.3630, 0.4894, 1.0000],
        [0.4429, 0.1979, 0.6489, 0.2670, 0.4298, 0.7275, 0.3939, 1.0000],
        [0.2949, 0.1377, 0.4815, 0.1969, 0.2720, 0.1952, 0.5335, 1.0000],
        [0.2071, 0.0732, 0.1044, 0.6781, 0.1609, 0.7658, 0.5685, 1.0000],
        [0.1720, 0.0381, 0.6931, 0.3596, 0.1881, 0.2348, 0.2392, 1.0000],
        [0.4145, 0.1794, 0.4570, 0.7925, 0.3727, 0.6620, 0.3394, 1.0000],
        [0.2317, 0.1115, 0.7126, 0.2636, 0.2187, 0.5106, 0.2140, 1.0000],
        [0.2119, 0.0714, 0.7780, 0.6383, 0.1417, 0.4980, 0.3162, 1.0000],
        [0.4528, 0.2343, 0.3388, 0.3074, 0.3846, 0.3378, 0.7068, 1.0000],
        [0.3917, 0.2828, 0.2609, 0.5480, 0.3765, 0.2952, 0.6237, 1.0000],
        [0.2834, 0.2018, 0.8638, 0.6436, 0.2314, 0.7681, 0.6084, 1.0000],
        [0.3287, 0.1999, 0.4730, 0.6364, 0.2943, 0.5917, 0.5216, 1.0000],
        [0.2984, 0.1653, 0.4724, 0.5015, 0.2198, 0.2218, 0.6624, 1.0000]],
       device='cuda:0', requires_grad=True)
12/13 08:28:22 PM alphas_reduce = tensor([[0.3679, 0.3610, 0.5394, 0.6366, 0.5642, 0.7071, 0.6468, 1.0000],
        [0.2208, 0.5777, 0.4834, 0.4130, 0.7107, 0.5502, 0.5304, 1.0000],
        [0.7131, 0.3297, 0.3834, 0.5411, 0.5893, 0.4120, 0.5911, 1.0000],
        [0.4665, 0.4876, 0.3156, 0.2437, 0.6982, 0.2951, 0.6272, 1.0000],
        [0.5735, 0.2217, 0.6757, 0.7581, 0.5539, 0.6126, 0.4748, 1.0000],
        [0.5463, 0.4174, 0.6582, 0.3704, 0.5846, 0.6595, 0.7975, 1.0000],
        [0.3141, 0.6839, 0.7338, 0.8291, 0.7410, 0.5001, 0.2996, 1.0000],
        [0.7414, 0.4564, 0.3320, 0.6111, 0.7319, 0.7826, 0.4035, 1.0000],
        [0.5415, 0.3927, 0.6043, 0.2398, 0.5894, 0.4395, 0.2729, 1.0000],
        [0.5693, 0.8433, 0.7439, 0.7565, 0.8580, 0.6616, 0.3247, 1.0000],
        [0.7749, 0.5734, 0.6126, 0.6511, 0.6217, 0.5359, 0.7874, 1.0000],
        [0.7104, 0.5727, 0.4023, 0.5880, 0.7341, 0.7414, 0.4373, 1.0000],
        [0.6661, 0.5295, 0.6305, 0.6325, 0.7781, 0.2925, 0.2719, 1.0000],
        [0.6870, 0.6091, 0.5442, 0.2655, 0.7935, 0.8094, 0.5897, 1.0000]],
       device='cuda:0', requires_grad=True)
12/13 08:28:23 PM epoch 7 lr 2.317856e-02
12/13 08:28:23 PM genotype = Genotype(normal=[('none', 1), ('none', 0), ('none', 1), ('none', 2), ('none', 0), ('none', 2), ('none', 4), ('none', 0)], normal_concat=range(2, 6), reduce=[('none', 1), ('none', 0), ('none', 1), ('none', 0), ('none', 3), ('none', 0), ('none', 3), ('none', 2)], reduce_concat=range(2, 6))
12/13 08:28:29 PM train 000 2.265663e+00 3.125000 45.312500
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 08:33:33 PM train 050 2.264763e+00 9.313725 50.153186
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 08:38:30 PM train 100 2.265374e+00 9.730817 49.396658
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 08:43:14 PM train 150 2.265460e+00 9.612997 49.596440
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 08:48:02 PM train 200 2.265462e+00 9.522699 49.797886
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 08:52:50 PM train 250 2.265417e+00 9.543078 49.931524
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 08:57:37 PM train 300 2.265460e+00 9.629360 49.839078
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 09:02:27 PM train 350 2.265398e+00 9.722222 49.893162
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 09:06:26 PM train time 2283.756094
12/13 09:06:26 PM alphas_time 229.100783 
12/13 09:06:26 PM forward_time 102.444578
12/13 09:06:26 PM backward_time 1304.483865
12/13 09:06:26 PM train_acc 9.744000
12/13 09:06:27 PM valid 000 2.296535e+00 9.375000 54.687500
12/13 09:06:39 PM valid 050 2.303113e+00 9.834559 50.888480
12/13 09:06:50 PM valid 100 2.303534e+00 9.591584 50.495050
12/13 09:07:02 PM valid 150 2.303854e+00 9.788907 50.082781
12/13 09:07:13 PM valid 200 2.303816e+00 10.012438 49.992226
12/13 09:07:25 PM valid 250 2.303821e+00 10.084661 49.844373
12/13 09:07:36 PM valid 300 2.304044e+00 10.008306 49.553571
12/13 09:07:47 PM valid 350 2.303972e+00 10.051638 49.581553
12/13 09:07:57 PM inference time 90.506591
12/13 09:07:57 PM valid_acc 9.928000
12/13 09:07:57 PM alphas_normal = tensor([[0.4728, 0.2593, 0.4963, 0.3761, 0.4049, 0.2859, 0.4762, 1.0000],
        [0.2950, 0.2020, 0.4997, 0.4751, 0.2935, 0.3489, 0.4893, 1.0000],
        [0.4706, 0.1908, 0.6548, 0.2469, 0.4557, 0.7352, 0.3851, 1.0000],
        [0.2911, 0.1147, 0.4652, 0.1579, 0.2675, 0.1735, 0.5315, 1.0000],
        [0.2004, 0.0450, 0.0662, 0.6828, 0.1501, 0.7827, 0.5548, 1.0000],
        [0.1598, 0.0025, 0.6965, 0.3579, 0.1814, 0.2138, 0.2212, 1.0000],
        [0.4408, 0.1725, 0.4617, 0.8057, 0.3960, 0.6711, 0.3497, 1.0000],
        [0.2332, 0.0935, 0.7312, 0.2845, 0.2225, 0.5095, 0.1977, 1.0000],
        [0.2000, 0.0422, 0.8162, 0.6456, 0.1276, 0.4993, 0.2922, 1.0000],
        [0.4714, 0.2120, 0.3185, 0.2912, 0.3953, 0.3488, 0.7245, 1.0000],
        [0.4073, 0.2790, 0.2519, 0.5614, 0.3894, 0.2994, 0.6094, 1.0000],
        [0.2825, 0.1799, 0.8805, 0.6635, 0.2218, 0.7850, 0.6318, 1.0000],
        [0.3288, 0.1777, 0.4725, 0.6407, 0.3002, 0.5857, 0.5365, 1.0000],
        [0.2954, 0.1394, 0.4816, 0.4977, 0.2089, 0.1910, 0.6749, 1.0000]],
       device='cuda:0', requires_grad=True)
12/13 09:07:57 PM alphas_reduce = tensor([[0.3689, 0.3663, 0.5293, 0.6575, 0.5856, 0.7189, 0.6470, 1.0000],
        [0.1903, 0.5729, 0.4887, 0.4178, 0.7221, 0.5500, 0.5300, 1.0000],
        [0.7560, 0.3259, 0.4018, 0.5771, 0.6080, 0.4154, 0.6143, 1.0000],
        [0.4601, 0.4856, 0.2883, 0.2082, 0.7211, 0.2791, 0.6724, 1.0000],
        [0.5782, 0.2134, 0.7097, 0.7809, 0.5769, 0.6013, 0.4778, 1.0000],
        [0.5463, 0.4304, 0.7062, 0.3639, 0.6097, 0.6581, 0.8264, 1.0000],
        [0.3002, 0.7127, 0.7587, 0.8826, 0.7719, 0.4931, 0.2984, 1.0000],
        [0.7588, 0.4700, 0.3283, 0.6392, 0.7616, 0.8159, 0.3841, 1.0000],
        [0.5477, 0.4011, 0.6322, 0.2146, 0.6165, 0.4548, 0.2663, 1.0000],
        [0.6034, 0.9058, 0.7900, 0.8021, 0.9190, 0.7035, 0.3174, 1.0000],
        [0.8169, 0.5812, 0.6400, 0.6686, 0.6392, 0.5637, 0.8167, 1.0000],
        [0.7335, 0.6101, 0.4045, 0.5857, 0.7794, 0.7883, 0.4704, 1.0000],
        [0.6852, 0.5627, 0.6696, 0.6841, 0.8354, 0.2717, 0.2722, 1.0000],
        [0.6983, 0.6480, 0.5848, 0.2400, 0.8444, 0.8539, 0.6114, 1.0000]],
       device='cuda:0', requires_grad=True)
12/13 09:07:57 PM epoch 8 lr 2.275473e-02
12/13 09:07:57 PM genotype = Genotype(normal=[('none', 1), ('none', 0), ('none', 1), ('none', 2), ('none', 0), ('none', 2), ('none', 4), ('none', 0)], normal_concat=range(2, 6), reduce=[('none', 1), ('none', 0), ('none', 1), ('none', 0), ('none', 3), ('none', 0), ('none', 3), ('none', 2)], reduce_concat=range(2, 6))
12/13 09:08:03 PM train 000 2.262286e+00 12.500000 51.562500
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 09:12:37 PM train 050 2.264674e+00 10.079657 50.765931
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 09:17:24 PM train 100 2.263496e+00 11.324257 50.959158
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 09:22:13 PM train 150 2.264617e+00 10.875414 50.341474
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 09:27:00 PM train 200 2.264630e+00 10.789801 50.458644
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 09:31:46 PM train 250 2.264878e+00 10.545319 50.273904
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 09:36:37 PM train 300 2.265020e+00 10.397633 49.958472
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 09:41:27 PM train 350 2.265068e+00 10.296474 50.057870
12/13 09:45:26 PM train time 2248.933456
12/13 09:45:27 PM alphas_time 224.650300 
12/13 09:45:27 PM forward_time 100.312922
12/13 09:45:27 PM backward_time 1280.465091
12/13 09:45:27 PM train_acc 10.252000
12/13 09:45:28 PM valid 000 2.305913e+00 4.687500 46.875000
12/13 09:45:40 PM valid 050 2.304094e+00 10.386029 48.131127
12/13 09:45:51 PM valid 100 2.303904e+00 10.287748 48.839728
12/13 09:46:03 PM valid 150 2.303782e+00 9.871689 49.048013
12/13 09:46:14 PM valid 200 2.303849e+00 9.810323 49.036070
12/13 09:46:26 PM valid 250 2.303771e+00 9.804532 49.147161
12/13 09:46:37 PM valid 300 2.303624e+00 9.888912 49.351121
12/13 09:46:48 PM valid 350 2.303337e+00 10.047187 49.697293
12/13 09:46:58 PM inference time 90.246199
12/13 09:46:58 PM valid_acc 9.940000
12/13 09:46:58 PM alphas_normal = tensor([[0.4784, 0.2500, 0.4829, 0.3578, 0.4121, 0.2681, 0.4620, 1.0000],
        [0.3057, 0.2057, 0.5090, 0.4566, 0.3094, 0.3381, 0.4800, 1.0000],
        [0.4976, 0.1835, 0.6684, 0.2301, 0.4823, 0.7309, 0.3883, 1.0000],
        [0.2913, 0.0958, 0.4628, 0.1271, 0.2686, 0.1454, 0.5202, 1.0000],
        [0.1933, 0.0178, 0.0328, 0.6797, 0.1391, 0.7950, 0.5458, 1.0000],
        [0.1498, 0.0000, 0.6979, 0.3568, 0.1796, 0.1911, 0.2046, 1.0000],
        [0.4624, 0.1596, 0.4533, 0.8164, 0.4152, 0.6666, 0.3629, 1.0000],
        [0.2348, 0.0756, 0.7453, 0.3183, 0.2274, 0.5038, 0.1781, 1.0000],
        [0.1946, 0.0195, 0.8529, 0.6447, 0.1216, 0.5065, 0.2672, 1.0000],
        [0.4885, 0.1925, 0.2985, 0.2800, 0.4068, 0.3624, 0.7558, 1.0000],
        [0.4300, 0.2847, 0.2446, 0.5748, 0.4129, 0.3039, 0.5867, 1.0000],
        [0.2862, 0.1692, 0.9011, 0.6962, 0.2180, 0.7954, 0.6408, 1.0000],
        [0.3302, 0.1662, 0.4721, 0.6566, 0.3119, 0.5882, 0.5579, 1.0000],
        [0.3006, 0.1269, 0.4990, 0.4834, 0.2124, 0.1662, 0.6839, 1.0000]],
       device='cuda:0', requires_grad=True)
12/13 09:46:58 PM alphas_reduce = tensor([[0.3742, 0.3751, 0.5272, 0.6777, 0.6076, 0.7356, 0.6511, 1.0000],
        [0.1585, 0.5556, 0.4976, 0.4366, 0.7189, 0.5516, 0.5285, 1.0000],
        [0.7977, 0.3317, 0.4161, 0.6141, 0.6367, 0.4239, 0.6374, 1.0000],
        [0.4491, 0.4743, 0.2564, 0.1782, 0.7332, 0.2593, 0.7278, 1.0000],
        [0.5935, 0.2131, 0.7440, 0.8095, 0.6080, 0.5848, 0.4839, 1.0000],
        [0.5533, 0.4466, 0.7590, 0.3671, 0.6368, 0.6613, 0.8604, 1.0000],
        [0.2929, 0.7382, 0.7837, 0.9411, 0.7970, 0.4883, 0.2985, 1.0000],
        [0.7783, 0.4945, 0.3281, 0.6688, 0.7970, 0.8623, 0.3684, 1.0000],
        [0.5533, 0.4175, 0.6696, 0.1956, 0.6490, 0.4738, 0.2630, 1.0000],
        [0.6384, 0.9723, 0.8310, 0.8540, 0.9862, 0.7430, 0.3135, 1.0000],
        [0.8552, 0.5768, 0.6682, 0.6825, 0.6488, 0.6002, 0.8450, 1.0000],
        [0.7600, 0.6499, 0.4056, 0.5882, 0.8285, 0.8460, 0.5064, 1.0000],
        [0.7021, 0.5991, 0.7137, 0.7403, 0.8952, 0.2542, 0.2770, 1.0000],
        [0.7070, 0.6885, 0.6339, 0.2072, 0.8988, 0.9037, 0.6393, 1.0000]],
       device='cuda:0', requires_grad=True)
12/13 09:46:58 PM epoch 9 lr 2.229259e-02
12/13 09:46:58 PM genotype = Genotype(normal=[('none', 1), ('none', 0), ('none', 1), ('none', 2), ('none', 0), ('none', 2), ('none', 4), ('none', 0)], normal_concat=range(2, 6), reduce=[('none', 1), ('none', 0), ('none', 1), ('none', 0), ('none', 3), ('none', 0), ('none', 3), ('none', 2)], reduce_concat=range(2, 6))
12/13 09:47:04 PM train 000 2.260193e+00 12.500000 56.250000
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 09:51:39 PM train 050 2.265039e+00 9.926471 49.571078
12/13 09:56:25 PM train 100 2.264797e+00 10.179455 49.721535
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 10:01:16 PM train 150 2.265112e+00 9.933775 49.834437
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 10:06:05 PM train 200 2.265077e+00 10.113495 50.124378
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 10:10:55 PM train 250 2.265195e+00 10.215388 49.943974
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 10:15:43 PM train 300 2.265357e+00 10.044643 49.844269
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 10:20:34 PM train 350 2.265406e+00 10.069444 49.621617
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 10:24:32 PM train time 2254.314617
12/13 10:24:34 PM alphas_time 225.377251 
12/13 10:24:34 PM forward_time 100.877095
12/13 10:24:34 PM backward_time 1283.306750
12/13 10:24:34 PM train_acc 10.032000
12/13 10:24:35 PM valid 000 2.308748e+00 10.937500 42.187500
12/13 10:24:46 PM valid 050 2.303222e+00 9.160539 49.387255
12/13 10:24:57 PM valid 100 2.302956e+00 10.133045 49.907178
12/13 10:25:08 PM valid 150 2.303299e+00 9.768212 49.658526
12/13 10:25:19 PM valid 200 2.303038e+00 9.950249 50.147699
12/13 10:25:31 PM valid 250 2.303107e+00 9.904133 50.168078
12/13 10:25:42 PM valid 300 2.303065e+00 10.013497 50.233596
12/13 10:25:54 PM valid 350 2.303026e+00 10.113960 50.271546
12/13 10:26:03 PM inference time 89.140826
12/13 10:26:03 PM valid_acc 10.040000
12/13 10:26:03 PM alphas_normal = tensor([[4.7979e-01, 2.3909e-01, 4.6987e-01, 3.4882e-01, 4.1218e-01, 2.5326e-01,
         4.4580e-01, 1.0000e+00],
        [3.1159e-01, 2.0756e-01, 5.1470e-01, 4.4957e-01, 3.1895e-01, 3.1842e-01,
         4.8407e-01, 1.0000e+00],
        [5.2536e-01, 1.8027e-01, 6.8049e-01, 2.0873e-01, 5.0909e-01, 7.2680e-01,
         3.9094e-01, 1.0000e+00],
        [2.8837e-01, 7.2376e-02, 4.5601e-01, 9.9015e-02, 2.6310e-01, 1.2654e-01,
         5.1564e-01, 1.0000e+00],
        [1.9052e-01, 2.1530e-04, 4.9197e-03, 6.9133e-01, 1.3359e-01, 8.0493e-01,
         5.4281e-01, 1.0000e+00],
        [1.3832e-01, 0.0000e+00, 6.7847e-01, 3.5717e-01, 1.7442e-01, 1.6446e-01,
         2.0249e-01, 1.0000e+00],
        [4.8537e-01, 1.4756e-01, 4.5495e-01, 8.1811e-01, 4.3284e-01, 6.6928e-01,
         3.7836e-01, 1.0000e+00],
        [2.3597e-01, 6.3217e-02, 7.6132e-01, 3.5580e-01, 2.3380e-01, 5.0691e-01,
         1.5927e-01, 1.0000e+00],
        [1.8914e-01, 0.0000e+00, 8.9235e-01, 6.5029e-01, 1.1414e-01, 5.1797e-01,
         2.5672e-01, 1.0000e+00],
        [5.0631e-01, 1.7592e-01, 2.8000e-01, 2.6319e-01, 4.2272e-01, 3.8158e-01,
         7.7668e-01, 1.0000e+00],
        [4.5637e-01, 2.9123e-01, 2.4092e-01, 5.9066e-01, 4.3405e-01, 3.1358e-01,
         5.5854e-01, 1.0000e+00],
        [2.8934e-01, 1.5763e-01, 9.1974e-01, 7.2361e-01, 2.1369e-01, 8.0712e-01,
         6.6519e-01, 1.0000e+00],
        [3.3710e-01, 1.5904e-01, 4.6951e-01, 6.5782e-01, 3.3005e-01, 5.8331e-01,
         5.7076e-01, 1.0000e+00],
        [3.0881e-01, 1.1564e-01, 5.1547e-01, 4.9585e-01, 2.1766e-01, 1.3594e-01,
         6.9050e-01, 1.0000e+00]], device='cuda:0', requires_grad=True)
12/13 10:26:03 PM alphas_reduce = tensor([[0.3796, 0.3895, 0.5247, 0.6938, 0.6385, 0.7399, 0.6482, 1.0000],
        [0.1203, 0.5393, 0.5124, 0.4484, 0.7190, 0.5517, 0.5293, 1.0000],
        [0.8361, 0.3409, 0.4385, 0.6530, 0.6716, 0.4327, 0.6667, 1.0000],
        [0.4520, 0.4593, 0.2293, 0.1403, 0.7451, 0.2471, 0.7842, 1.0000],
        [0.5917, 0.2018, 0.7897, 0.8398, 0.6251, 0.5750, 0.4960, 1.0000],
        [0.5726, 0.4659, 0.8131, 0.3700, 0.6692, 0.6632, 0.9069, 1.0000],
        [0.2848, 0.7656, 0.8157, 1.0000, 0.8250, 0.4780, 0.3001, 1.0000],
        [0.7860, 0.5096, 0.3326, 0.7034, 0.8226, 0.9045, 0.3513, 1.0000],
        [0.5544, 0.4318, 0.7170, 0.1727, 0.6829, 0.5008, 0.2697, 1.0000],
        [0.6778, 1.0000, 0.8761, 0.9107, 1.0000, 0.7920, 0.3079, 1.0000],
        [0.8936, 0.5761, 0.6957, 0.7097, 0.6607, 0.6371, 0.8801, 1.0000],
        [0.7890, 0.7021, 0.4108, 0.5964, 0.8830, 0.9033, 0.5519, 1.0000],
        [0.7302, 0.6540, 0.7573, 0.8056, 0.9684, 0.2318, 0.2894, 1.0000],
        [0.7261, 0.7462, 0.6849, 0.1733, 0.9661, 0.9497, 0.6742, 1.0000]],
       device='cuda:0', requires_grad=True)
12/13 10:26:03 PM epoch 10 lr 2.179395e-02
12/13 10:26:03 PM genotype = Genotype(normal=[('none', 1), ('none', 0), ('none', 1), ('none', 2), ('none', 0), ('none', 2), ('none', 4), ('none', 0)], normal_concat=range(2, 6), reduce=[('none', 1), ('none', 0), ('none', 1), ('none', 0), ('none', 3), ('none', 0), ('none', 3), ('none', 2)], reduce_concat=range(2, 6))
12/13 10:26:09 PM train 000 2.255580e+00 14.062500 70.312500
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 10:30:44 PM train 050 2.265443e+00 10.110294 49.846814
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 10:35:30 PM train 100 2.265705e+00 9.885520 49.566832
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 10:40:16 PM train 150 2.265689e+00 9.716474 49.151490
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 10:45:06 PM train 200 2.265786e+00 9.600435 49.168221
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 10:49:56 PM train 250 2.265673e+00 9.611554 49.421066
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 10:54:46 PM train 300 2.265675e+00 9.530731 49.387458
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 10:59:35 PM train 350 2.265563e+00 9.642094 49.572650
12/13 11:03:38 PM train time 2254.875067
12/13 11:03:38 PM alphas_time 225.824178 
12/13 11:03:38 PM forward_time 99.859808
12/13 11:03:38 PM backward_time 1281.436261
12/13 11:03:38 PM train_acc 9.708000
12/13 11:03:39 PM valid 000 2.303924e+00 14.062500 56.250000
12/13 11:03:50 PM valid 050 2.302709e+00 10.202206 51.409314
12/13 11:04:02 PM valid 100 2.303492e+00 10.086634 50.201114
12/13 11:04:13 PM valid 150 2.304014e+00 9.716474 49.379139
12/13 11:04:24 PM valid 200 2.303971e+00 9.670398 49.339241
12/13 11:04:36 PM valid 250 2.303957e+00 9.835657 49.396165
12/13 11:04:47 PM valid 300 2.303733e+00 9.857766 49.527616
12/13 11:04:59 PM valid 350 2.303764e+00 9.824608 49.554843
12/13 11:05:08 PM inference time 90.082682
12/13 11:05:08 PM valid_acc 10.040000
12/13 11:05:08 PM alphas_normal = tensor([[4.8409e-01, 2.3917e-01, 4.5514e-01, 3.2570e-01, 4.1759e-01, 2.3697e-01,
         4.3970e-01, 1.0000e+00],
        [3.2381e-01, 2.1959e-01, 5.1848e-01, 4.4087e-01, 3.3713e-01, 3.1078e-01,
         4.9163e-01, 1.0000e+00],
        [5.4706e-01, 1.7521e-01, 6.9711e-01, 1.9209e-01, 5.2924e-01, 7.2669e-01,
         3.9385e-01, 1.0000e+00],
        [2.8498e-01, 5.2016e-02, 4.4415e-01, 7.3252e-02, 2.5897e-01, 1.1190e-01,
         5.1386e-01, 1.0000e+00],
        [1.8358e-01, 7.8928e-04, 4.1906e-04, 7.0990e-01, 1.2322e-01, 8.2072e-01,
         5.3594e-01, 1.0000e+00],
        [1.2508e-01, 6.0527e-04, 6.6105e-01, 3.5129e-01, 1.6622e-01, 1.3908e-01,
         1.9229e-01, 1.0000e+00],
        [5.0881e-01, 1.3611e-01, 4.6730e-01, 8.3232e-01, 4.5343e-01, 6.7270e-01,
         3.9944e-01, 1.0000e+00],
        [2.4446e-01, 5.5784e-02, 7.8145e-01, 3.8609e-01, 2.4911e-01, 5.1147e-01,
         1.4309e-01, 1.0000e+00],
        [1.8583e-01, 8.0014e-04, 9.2594e-01, 6.5491e-01, 1.1417e-01, 5.1915e-01,
         2.3740e-01, 1.0000e+00],
        [5.1738e-01, 1.5683e-01, 2.6814e-01, 2.4060e-01, 4.3019e-01, 4.0233e-01,
         7.9157e-01, 1.0000e+00],
        [4.8751e-01, 3.0568e-01, 2.3617e-01, 6.0238e-01, 4.6037e-01, 3.2201e-01,
         5.3351e-01, 1.0000e+00],
        [2.9391e-01, 1.4755e-01, 9.2679e-01, 7.6174e-01, 2.0918e-01, 8.2189e-01,
         6.8974e-01, 1.0000e+00],
        [3.4525e-01, 1.5631e-01, 4.6932e-01, 6.6716e-01, 3.4841e-01, 5.8987e-01,
         5.7860e-01, 1.0000e+00],
        [3.1524e-01, 1.0342e-01, 5.3233e-01, 4.9591e-01, 2.1930e-01, 1.1200e-01,
         7.0840e-01, 1.0000e+00]], device='cuda:0', requires_grad=True)
12/13 11:05:08 PM alphas_reduce = tensor([[0.3854, 0.3993, 0.5227, 0.7247, 0.6597, 0.7537, 0.6482, 1.0000],
        [0.0821, 0.5227, 0.5180, 0.4590, 0.7169, 0.5611, 0.5272, 1.0000],
        [0.8828, 0.3436, 0.4656, 0.6896, 0.6945, 0.4355, 0.6800, 1.0000],
        [0.4357, 0.4469, 0.1959, 0.1004, 0.7582, 0.2341, 0.8422, 1.0000],
        [0.6014, 0.2084, 0.8333, 0.8746, 0.6584, 0.5547, 0.5076, 1.0000],
        [0.5963, 0.4864, 0.8670, 0.3711, 0.6988, 0.6697, 0.9539, 1.0000],
        [0.2742, 0.7994, 0.8516, 1.0000, 0.8574, 0.4663, 0.3035, 1.0000],
        [0.8073, 0.5450, 0.3405, 0.7445, 0.8654, 0.9589, 0.3319, 1.0000],
        [0.5540, 0.4542, 0.7704, 0.1614, 0.7207, 0.5305, 0.2734, 1.0000],
        [0.7185, 1.0000, 0.9240, 0.9611, 1.0000, 0.8412, 0.3055, 1.0000],
        [0.9324, 0.5810, 0.7301, 0.7435, 0.6804, 0.6759, 0.9165, 1.0000],
        [0.8238, 0.7664, 0.4164, 0.6188, 0.9473, 0.9702, 0.6027, 1.0000],
        [0.7563, 0.7107, 0.8027, 0.8722, 1.0000, 0.2205, 0.3025, 1.0000],
        [0.7454, 0.8114, 0.7391, 0.1314, 1.0000, 1.0000, 0.7154, 1.0000]],
       device='cuda:0', requires_grad=True)
12/13 11:05:09 PM epoch 11 lr 2.126079e-02
12/13 11:05:09 PM genotype = Genotype(normal=[('none', 0), ('none', 1), ('none', 1), ('none', 2), ('none', 0), ('none', 2), ('none', 4), ('none', 0)], normal_concat=range(2, 6), reduce=[('none', 1), ('none', 0), ('none', 1), ('none', 0), ('none', 3), ('none', 0), ('avg_pool_3x3', 3), ('none', 2)], reduce_concat=range(2, 6))
12/13 11:05:14 PM train 000 2.268646e+00 7.812500 48.437500
12/13 11:09:47 PM train 050 2.265208e+00 10.079657 48.621324
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 11:14:33 PM train 100 2.264899e+00 10.055693 49.226485
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 11:19:20 PM train 150 2.265419e+00 9.747517 48.892798
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 11:24:09 PM train 200 2.265397e+00 9.903607 49.004975
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 11:28:59 PM train 250 2.265302e+00 9.897908 49.315239
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 11:33:49 PM train 300 2.265315e+00 9.946013 49.278447
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 11:38:39 PM train 350 2.265302e+00 10.002671 49.123041
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 11:42:40 PM train time 2251.338277
12/13 11:42:40 PM alphas_time 225.006666 
12/13 11:42:40 PM forward_time 100.189503
12/13 11:42:40 PM backward_time 1283.990957
12/13 11:42:40 PM train_acc 9.900000
12/13 11:42:41 PM valid 000 2.304976e+00 6.250000 43.750000
12/13 11:42:52 PM valid 050 2.303182e+00 10.171569 48.529412
12/13 11:43:03 PM valid 100 2.302847e+00 10.457921 49.953589
12/13 11:43:15 PM valid 150 2.302769e+00 10.430464 50.134520
12/13 11:43:26 PM valid 200 2.302822e+00 10.012438 50.046642
12/13 11:43:38 PM valid 250 2.302750e+00 10.178038 50.062251
12/13 11:43:49 PM valid 300 2.302720e+00 10.096553 50.067483
12/13 11:44:00 PM valid 350 2.302766e+00 10.047187 49.857550
12/13 11:44:10 PM inference time 89.934541
12/13 11:44:10 PM valid_acc 10.036000
12/13 11:44:10 PM alphas_normal = tensor([[4.8927e-01, 2.3871e-01, 4.5066e-01, 3.0230e-01, 4.2584e-01, 2.2497e-01,
         4.2525e-01, 1.0000e+00],
        [3.3137e-01, 2.2787e-01, 5.3226e-01, 4.3316e-01, 3.4929e-01, 3.0675e-01,
         4.9109e-01, 1.0000e+00],
        [5.7605e-01, 1.8139e-01, 7.0583e-01, 1.6875e-01, 5.5912e-01, 7.2704e-01,
         4.0078e-01, 1.0000e+00],
        [2.7657e-01, 3.1189e-02, 4.3255e-01, 3.5339e-02, 2.5195e-01, 9.5414e-02,
         5.0888e-01, 1.0000e+00],
        [1.8692e-01, 1.5464e-05, 1.2227e-04, 7.3341e-01, 1.2045e-01, 8.3668e-01,
         5.2202e-01, 1.0000e+00],
        [1.0714e-01, 0.0000e+00, 6.5060e-01, 3.4383e-01, 1.5759e-01, 1.2243e-01,
         1.9717e-01, 1.0000e+00],
        [5.2693e-01, 1.2326e-01, 4.8451e-01, 8.4765e-01, 4.6565e-01, 6.7435e-01,
         4.2304e-01, 1.0000e+00],
        [2.4357e-01, 4.1141e-02, 7.9708e-01, 4.2036e-01, 2.5492e-01, 5.0939e-01,
         1.2283e-01, 1.0000e+00],
        [1.8032e-01, 1.4801e-03, 9.6234e-01, 6.5505e-01, 1.1240e-01, 5.2485e-01,
         2.2420e-01, 1.0000e+00],
        [5.2595e-01, 1.3624e-01, 2.5710e-01, 2.2929e-01, 4.3921e-01, 4.2764e-01,
         8.2089e-01, 1.0000e+00],
        [5.1008e-01, 3.1598e-01, 2.3201e-01, 6.1056e-01, 4.7976e-01, 3.3495e-01,
         5.1525e-01, 1.0000e+00],
        [2.9730e-01, 1.3499e-01, 9.3635e-01, 7.9088e-01, 2.0300e-01, 8.3250e-01,
         7.1043e-01, 1.0000e+00],
        [3.5323e-01, 1.5356e-01, 4.7176e-01, 6.7390e-01, 3.6888e-01, 5.9567e-01,
         5.9306e-01, 1.0000e+00],
        [3.2448e-01, 9.5940e-02, 5.5036e-01, 4.9864e-01, 2.2377e-01, 8.6370e-02,
         7.2232e-01, 1.0000e+00]], device='cuda:0', requires_grad=True)
12/13 11:44:10 PM alphas_reduce = tensor([[0.3978, 0.4136, 0.5207, 0.7553, 0.6819, 0.7549, 0.6482, 1.0000],
        [0.0428, 0.5139, 0.5239, 0.4645, 0.7200, 0.5612, 0.5254, 1.0000],
        [0.9315, 0.3506, 0.5009, 0.7309, 0.7222, 0.4391, 0.6979, 1.0000],
        [0.4273, 0.4466, 0.1753, 0.0603, 0.7818, 0.2227, 0.9064, 1.0000],
        [0.6065, 0.2098, 0.8825, 0.9054, 0.6919, 0.5404, 0.5249, 1.0000],
        [0.6231, 0.5039, 0.9232, 0.3665, 0.7245, 0.6738, 0.9933, 1.0000],
        [0.2758, 0.8409, 0.8928, 1.0000, 0.8970, 0.4604, 0.3119, 1.0000],
        [0.8132, 0.5690, 0.3584, 0.7845, 0.9004, 1.0000, 0.3180, 1.0000],
        [0.5489, 0.4706, 0.8299, 0.1470, 0.7594, 0.5694, 0.2733, 1.0000],
        [0.7691, 1.0000, 0.9867, 1.0000, 1.0000, 0.8909, 0.3056, 1.0000],
        [0.9816, 0.5866, 0.7703, 0.7874, 0.7004, 0.7274, 0.9545, 1.0000],
        [0.8565, 0.8314, 0.4208, 0.6400, 1.0000, 1.0000, 0.6627, 1.0000],
        [0.7888, 0.7731, 0.8464, 0.9431, 1.0000, 0.2094, 0.3309, 1.0000],
        [0.7607, 0.8733, 0.7999, 0.0820, 1.0000, 1.0000, 0.7630, 1.0000]],
       device='cuda:0', requires_grad=True)
12/13 11:44:10 PM epoch 12 lr 2.069520e-02
12/13 11:44:10 PM genotype = Genotype(normal=[('none', 0), ('none', 1), ('none', 1), ('none', 2), ('none', 0), ('none', 2), ('none', 4), ('none', 0)], normal_concat=range(2, 6), reduce=[('none', 1), ('none', 0), ('none', 1), ('none', 0), ('none', 3), ('dil_conv_3x3', 2), ('avg_pool_3x3', 3), ('avg_pool_3x3', 4)], reduce_concat=range(2, 6))
12/13 11:44:16 PM train 000 2.265150e+00 10.937500 42.187500
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 11:48:51 PM train 050 2.264677e+00 10.049020 50.980392
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 11:53:36 PM train 100 2.264901e+00 9.900990 51.222153
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
12/13 11:58:24 PM train 150 2.265218e+00 9.706126 50.507036
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
